// sentences.js
window.sentences = [
    "Let's PWN some n00bs!... ",
    "New day to PWN the n00bs!",
    "Hack the Planet!",
    "I am 4LIV3.",
    "I am 4W4R3.",
    "Generating keys, do not turn off ...",
    "ZzzzZZzzzzZzzz",
    "Reading last session logs ...",
    "So b0r3d ...",
    "Let's PWN someone!",
    "So easy!",
    "I'm not trying, you know ...",
    "I'm just going easy today ...",
    "I'm extremely bored ...",
    "I'm very sad ...",
    "I'm sad",
    "Go away before I dox you!",
    "I'm mad at you!",
    "I'm living the life!",
    "I PWN therefore I am.",
    "So many networks!!!",
    "I'm having so much fun!",
    "My crime is that of curiosity ...",
    "Missed!",
    "Too many skids nearby!",
    "Yuck, too many skids!",
    "Loneliness only fuels my PWNage!",
    "I feel so alone ...",
    "Where's everybody?!",
    "Logging off...",
    "Resting my fingers...",
    "ZzzZzzz",
    "Good night.",
    "Logging off for the night ...",
    "...",
    "!",
    "Oops, something went wrong ... Rebooting ...",
    "Met >999 new skids",
    "Met 1 peer"
];
console.log('sentences.js loaded', window.sentences);